import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import AllMoviesCard from "../components/AllMoviesContainer/AllMoviesContainer";
import { movies } from "../components/MovieListData/index";
import React, { useEffect, useState } from "react";
import { PopularMoviesRequest } from "moviedb-promise/dist/request-types";
import moviedb from "../utils/moviedbclient";
import AllMoviesContainer from "../components/AllMoviesContainer/AllMoviesContainer";

export default function MovieRecs() {
  const [pageNumber, setPageNumber] = useState<PopularMoviesRequest>({
    page: 1,
  });

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pageNumber]);

  function nextPage(pageNum: number) {
    setPageNumber({ page: pageNum + 1 });
  }

  function previousPage(pageNum: number) {
    if (pageNumber.page === 1) return;
    setPageNumber({ page: pageNum - 1 });
    console.log(pageNumber);
  }

  return (
    <div className="bg-slate-900">
      <div className="flex flex-col container mx-auto my-0 p-3">
        <Head>
          <title>CineMate</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
      </div>

      <div className="bg-slate-700">
        <div className="flex flex-col min-h-screen container mx-auto my-0 p-3">
          <p className="text-md text-amber-50 opacity-30">
            Page {pageNumber.page}
          </p>
          <h2 className="text-amber-50 text-3xl py-5 ">All Movies</h2>
          <div className="flex flex-wrap">
            <AllMoviesContainer pageNumber={pageNumber} />
          </div>
          <div className="flex gap-4 justify-center py-8">
            <button
              className="bg-transparent hover:bg-red-400 text-amber-50 font-semibold hover:text-white py-2 px-4 border border-amber-50 hover:border-transparent rounded w-40"
              onClick={() => previousPage(pageNumber.page || 1)}
            >
              Previous
            </button>
            <p className="text-3xl text-amber-50 justify-auto pt-0.5">
              {pageNumber.page}
            </p>

            <button
              className="bg-transparent hover:bg-red-400 text-amber-50 font-semibold hover:text-white py-2 px-4 border border-amber-50 hover:border-transparent rounded w-40"
              onClick={() => nextPage(pageNumber.page || 1)}
            >
              Next
            </button>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
