import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Subscription from "../components/Subscription/subscription";

export default function Home() {
  const session = useSession();
  return (
    <div className="bg-slate-800">
      <div className="flex flex-col container mx-auto my-0 p-3">
        <Head>
          <title>CineMate</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
      </div>
      <Hero />
      <Subscription />
      <div className="flex flex-col min-h-screen container mx-auto my-0 p-3">
        <main className="flex-1 text-amber-50">
          {session && <p>User logged in {session.user.email}</p>}
        </main>
      </div>
      <Footer />
    </div>
  );
}
