import React from "react";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { useSupabaseClient, useUser } from "@supabase/auth-helpers-react";
import Head from "next/head";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import { useRouter } from "next/router";

export default function Login() {
  const user = useUser();
  const supabase = useSupabaseClient();
  const router = useRouter();

  if (user) {
    router.push("/");
  }

  return (
    <div className="flex flex-col bg-slate-900 h-screen">
      <Head>
        <title>CineMate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Header disableButton={true} />

      <div className="bg-slate-800 flex-1 flex flex-col">
        <div className="container flex flex-grow p-8 mx-auto md:max-w-2xl">
          {!user ? (
            <div className="w-full">
              <h1 className="text-4xl text-amber-50 font-semibold mb-16 text-center">
                Welcome Back{" "}
                <span className="text-xs">to the school of code</span>
              </h1>
              <Auth
                supabaseClient={supabase}
                theme="dark"
                magicLink
                redirectTo="http://localhost:3000/"
                localization={{
                  variables: {
                    sign_up: {
                      button_label: "SIGN UP",
                    },
                    sign_in: {
                      button_label: "SIGN IN",
                    },
                  },
                }}
                appearance={{
                  theme: ThemeSupa,
                  variables: {
                    default: {
                      colors: {
                        anchorTextColor: "#fffbeb",
                        brand: "#F87171",
                        brandAccent: "#F87171",
                        brandButtonText: "#334155",
                        defaultButtonBackground: "#818CF8",
                        defaultButtonBackgroundHover: "#C7D2FE",
                        defaultButtonBorder: "#818CF8",
                        defaultButtonText: "#1E293B",
                        dividerBackground: "#F59E0B",
                        inputBackground: "#1E293B",
                        inputText: "#fffbeb",
                        inputPlaceholder: "#1E293B",
                        inputLabelText: "#fffbeb",
                        inputBorder: "#fffbeb",
                        inputBorderHover: "#D97706",
                        inputBorderFocus: "#D97706",
                        messageText: "#A3E635",
                        messageTextDanger: "#dc2626",
                      },
                      space: {
                        spaceSmall: "4px",
                        spaceMedium: "8px",
                        spaceLarge: "16px",
                        labelBottomMargin: "8px",
                        anchorBottomMargin: "4px",
                        emailInputSpacing: "4px",
                        socialAuthSpacing: "4px",
                        buttonPadding: "10px 15px",
                        inputPadding: "10px 15px",
                      },
                      fontSizes: {
                        baseBodySize: "13px",
                        baseInputSize: "14px",
                        baseLabelSize: "14px",
                        baseButtonSize: "14px",
                      },
                      fonts: {
                        bodyFontFamily: `ui-sans-serif, sans-serif`,
                        buttonFontFamily: `ui-sans-serif, sans-serif`,
                        inputFontFamily: `ui-sans-serif, sans-serif`,
                        labelFontFamily: `ui-sans-serif, sans-serif`,
                      },
                      // fontWeights: {},
                      // lineHeights: {},
                      // letterSpacings: {},
                      // sizes: {},
                      borderWidths: {
                        buttonBorderWidth: "1px",
                        inputBorderWidth: "1px",
                      },
                      // borderStyles: {},
                      radii: {
                        borderRadiusButton: "4px",
                        buttonBorderRadius: "4px",
                        inputBorderRadius: "4px",
                      },
                      // shadows: {},
                      // zIndices: {},
                      // transitions: {},
                    },
                  },
                }}
              />
            </div>
          ) : (
            <p>User logged in {user.email}</p>
          )}
        </div>
        <Footer />
      </div>
    </div>
  );
}
