import React from "react";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { useSupabaseClient, useUser } from "@supabase/auth-helpers-react";
import Head from "next/head";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import { useRouter } from "next/router";

export default function Login() {
  const user = useUser();
  const supabase = useSupabaseClient();
  const router = useRouter();

  if (user) {
    router.push("/");
  }

  return (
    <div className="bg-slate-900">
      <div className="flex flex-col container mx-auto my-0 p-3">
        <Head>
          <title>CineMate</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header disableButton={true} />
      </div>
      <div className="bg-slate-700">
        <div className="flex flex-col min-h-screen container mx-auto my-0 p-3">
          <main className="flex-1 text-amber-50">
            {!user ? (
              <Auth
                supabaseClient={supabase}
                appearance={{ theme: ThemeSupa }}
                theme="dark"
                magicLink
                redirectTo="http://localhost:3000/"
              />
            ) : (
              <p>User logged in {user.email}</p>
            )}
          </main>
        </div>
      </div>
      <Footer />
    </div>
  );
}
