import {
  useSession,
  useSupabaseClient,
  useUser,
} from "@supabase/auth-helpers-react";
import { useRouter } from "next/router";
import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import RecommendedMovieCard from "../components/RecommendedContainer/RecommendedContainer";
import { useEffect, useLayoutEffect } from "react";
import { GetServerSidePropsContext } from "next";
import {
  User,
  createServerSupabaseClient,
} from "@supabase/auth-helpers-nextjs";
import RecommendedContainer from "../components/RecommendedContainer/RecommendedContainer";

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  // Create authenticated Supabase Client
  const supabase = createServerSupabaseClient(ctx);
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session)
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };

  // Run queries with RLS on the server
  const { data } = await supabase.from("users").select("*");

  return {
    props: {
      initialSession: session,
      user: session.user,
      data: data ?? [],
    },
  };
};

export default function MovieRecs({ user }: { user: User }) {
  return (
    <div className="bg-slate-900">
      <div className="flex flex-col container mx-auto my-0 p-3">
        <Head>
          <title>CineMate</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
      </div>

      <div className="bg-slate-700">
        <div className="flex flex-col min-h-screen container mx-auto my-0 p-3">
          <h2 className="text-amber-50 text-2xl py-5">
            Your Recommended Movies
          </h2>
          <div className="flex flex-wrap">
            {user ? <RecommendedContainer user={user} /> : null}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
