import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";

import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import AccountProfile from "../components/AccountProfile/AccountProfile";

export default function Profile() {
  const session = useSession();
  const supabase = useSupabaseClient();

  return (
    <div className="bg-slate-900">
      <div className="flex flex-col container mx-auto my-0 p-3">
        <Head>
          <title>CineMate</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
      </div>

      {!session ? (
        <Auth
          supabaseClient={supabase}
          appearance={{ theme: ThemeSupa }}
          theme="dark"
        />
      ) : (
        <AccountProfile session={session} />
      )}

      <Footer />
    </div>
  );
}
